import Navbar from "@/components/navbar";
import PullToRefresh from "@/components/pull-to-refresh";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Andromeda",
  description: "Generated by create next app",
  generator: "Next.js",
  manifest: "/manifest.json",
  keywords: ["nextjs", "next14", "pwa", "next-pwa"],
  viewport:
    "minimum-scale=1, initial-scale=1, width=device-width, shrink-to-fit=no, viewport-fit=cover",
  icons: [
    { rel: "apple-touch-icon", url: "icons/andromeda-logo-128x128.png" },
    { rel: "icon", url: "icons/andromeda-logo-128x128.png" },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} antialiased flex flex-col h-screen`}>
        <main className="h-full flex-1 overflow-y-auto">{children}</main>
        <Navbar />
        <PullToRefresh />
      </body>
    </html>
  );
}
